#!/usr/bin/env python3
"""Render personal instructions and expose shared skills; --check is read-only."""
import argparse
import hashlib
from pathlib import Path
import shutil
import sys

ROOT = Path(__file__).resolve().parent
USER_DIR = ROOT.parents[1]
SKILLS = ('ai-image', 'brain', 'claudex', 'handoff', 'humanizer',
          'learn', 'make-film', 'spell-out')
TARGETS = {
    'claude': USER_DIR / '.claude/CLAUDE.md',
    'codex': USER_DIR / '.codex/AGENTS.md',
    'opencode': USER_DIR / '.config/opencode/AGENTS.md',
}

def rendered_files(skills=SKILLS):
    common = (ROOT / 'instructions/common.md').read_text()
    for host, target in TARGETS.items():
        adapter = (ROOT / f'instructions/{host}.md').read_text()
        yield target, ('<!-- Generated by ~/.config/agent-shared/sync.py. '
                       'Edit ~/.config/agent-shared/instructions/ and run the sync. -->\n\n'
                       + common.rstrip() + '\n\n' + adapter)
    for name in skills:
        yield USER_DIR / f'.config/opencode/commands/{name}.md', (
            f'---\ndescription: Run the personal {name} skill\n---\n\n'
            f'Load the `{name}` skill using the native skill tool, then follow it '
            f'for this explicit /{name} request.\n\nArguments: $ARGUMENTS\n')
    if not skills:
        return
    yield USER_DIR / '.config/opencode/commands/gpt-image.md', (
        '---\ndescription: Legacy alias for ai-image\n---\n\n'
        'Load the `ai-image` skill and follow it for this explicit /gpt-image request.\n\n'
        'Arguments: $ARGUMENTS\n')

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--instructions-only', action='store_true',
                        help='render the three instruction files; skip skill links and command wrappers')
    args = parser.parse_args()
    skills = () if args.instructions_only else SKILLS
    # Validate all link targets before making changes.
    for name in skills:
        if not (USER_DIR / f'.claude/skills/{name}/SKILL.md').is_file():
            raise SystemExit(f'Missing skill: {name}')
        link = USER_DIR / f'.agents/skills/{name}'
        source = USER_DIR / f'.claude/skills/{name}'
        if (link.exists() or link.is_symlink()) and link.resolve() != source.resolve():
            raise SystemExit(f'Refusing to replace unrelated skill: {link}')
    mismatches = []
    for target, content in rendered_files(skills):
        data = content.encode()
        if target.is_file() and target.read_bytes() == data:
            continue
        mismatches.append(str(target))
        if args.check:
            continue
        if target.exists():
            digest = hashlib.sha256(target.read_bytes()).hexdigest()[:16]
            backup = ROOT / 'backups/generated' / target.relative_to(USER_DIR)
            backup = backup.with_name(backup.name + '.' + digest)
            backup.parent.mkdir(parents=True, exist_ok=True)
            if not backup.exists():
                shutil.copy2(target, backup)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        print(f'Wrote {target}')
    for name in skills:
        link = USER_DIR / f'.agents/skills/{name}'
        if link.exists():
            continue
        mismatches.append(str(link))
        if not args.check:
            link.parent.mkdir(parents=True, exist_ok=True)
            link.symlink_to(USER_DIR / f'.claude/skills/{name}', target_is_directory=True)
            print(f'Linked {link}')
    if args.check:
        if mismatches:
            print('Out of sync:\n' + '\n'.join(mismatches))
            return 1
        print('Instructions, command wrappers, and nine shared skill links are in sync.')
    return 0

if __name__ == '__main__':
    sys.exit(main())
